/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Window-Control.h
 #	source generated by 4D Plugin Wizard
 #	Project : Window Control
 #	author : miyako
 #	2019/09/30
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_WINDOW_CONTROL_H
#define PLUGIN_WINDOW_CONTROL_H

#include "4DPluginAPI.h"

#import <AppKit/AppKit.h>

#pragma mark -

void WINDOW_SET_ENABLED(PA_PluginParameters params);
void WINDOW_Get_enabled(PA_PluginParameters params);
void WINDOW_SET_ICON(PA_PluginParameters params);
void WINDOW_Get_icon(PA_PluginParameters params);

void WINDOW_MINIATURIZE(PA_PluginParameters params);
void WINDOW_DEMINIATURIZE(PA_PluginParameters params);
void WINDOW_Is_miniaturized(PA_PluginParameters params);

typedef enum {
    
    Window_close_button = 0,
    Window_minimize_button = 1,
    Window_zoom_button = 2,
    Window_document_modified = 3
    
} Window_Option;

#endif /* PLUGIN_WINDOW_CONTROL_H */
